const { PORTE, OPEN_AI_API_KEY, TELEGRAM_TOKEN, WEBHOOK_DOMAIN, MONGO_CONNECTION_URL, ERROR_REPORT_CHAT_ID, REPLICATE_API_TOKEN, WHITE_LIST_CHAT_ID,PAYMENT_PROVIDER_TOKEN } =
  process.env as {
    PORTE: string;
    OPEN_AI_API_KEY: string;
    TELEGRAM_TOKEN: string;
    WEBHOOK_DOMAIN: string;
    MONGO_CONNECTION_URL: string;
    ERROR_REPORT_CHAT_ID: string;
    REPLICATE_API_TOKEN: string;
    WHITE_LIST_CHAT_ID: string;
    PAYMENT_PROVIDER_TOKEN: string;
  };

export default {
  PORTE,
  OPEN_AI_API_KEY,
  TELEGRAM_TOKEN,
  WEBHOOK_DOMAIN,
  MONGO_CONNECTION_URL,
  ERROR_REPORT_CHAT_ID,
  REPLICATE_API_TOKEN,
  WHITE_LIST_CHAT_ID,
  PAYMENT_PROVIDER_TOKEN
};
